<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SportTypeSeeder extends Seeder
{
    /**
     * Seeds default English sport types.
     */
    public function run(): void
    {
        foreach ($this->sportTypes() as $name) {
            DB::table('sport_types')->updateOrInsert(
                ['name' => $name],
                ['parent_id' => null],
            );
        }
    }

    /**
     * Returns sport types used as default catalog values.
     *
     * @return string[]
     */
    private function sportTypes(): array
    {
        return [
            'Football',
            'Futsal',
            'American Football',
            'Basketball',
            'Volleyball',
            'Beach Volleyball',
            'Hockey',
            'Ice Hockey',
            'Indoor Hockey',
            'Field Hockey',
            'Bandy',
            'Tennis',
            'Table Tennis',
            'Badminton',
            'Running',
            'Athletics',
            'Swimming',
            'Cycling',
            'Fitness',
            'Yoga',
            'Boxing',
            'Martial Arts',
            'Mixed Martial Arts',
            'Wrestling',
            'Freestyle Wrestling',
            'Greco-Roman Wrestling',
            'Belt Wrestling',
            'Karate',
            'Goju-Ryu Karate',
            'Judo',
            'Sambo',
            'Aikido',
            'Taekwondo',
            'Kickboxing',
            'Kudo',
            'Wushu',
            'Hapkido',
            'Capoeira',
            'Muay Thai',
            'Jiu-Jitsu',
            'Grappling',
            'Pankration',
            'Hand-to-Hand Combat',
            'Combined Martial Arts',
            'Motorsport',
            'Formula 1',
            'Formula 1 Powerboat Racing',
            'Karting',
            'Motorcycle Sport',
            'Motoball',
            'Radio Sport',
            'Equestrian',
            'Polo',
            'Golf',
            'Rugby',
            'Rugby League',
            'Baseball',
            'Softball',
            'Handball',
            'Beach Handball',
            'Dance',
            'DanceSport',
            'Skiing',
            'Alpine Skiing',
            'Cross-Country Skiing',
            'Nordic Combined',
            'Ski Jumping',
            'Freestyle Skiing',
            'Snowboarding',
            'Figure Skating',
            'Speed Skating',
            'Short Track Speed Skating',
            'Chess',
            'Esports',
            'Pilates',
            'Climbing',
            'Sport Climbing',
            'Triathlon',
            'Duathlon',
            'Racing',
            'Billiards',
            'Skateboarding',
            'Surfing',
            'Rowing',
            'Canoe Sprint',
            'Canoe Slalom',
            'Canoe Polo',
            'Kayaking',
            'Dragon Boat Racing',
            'Gymnastics',
            'Artistic Gymnastics',
            'Rhythmic Gymnastics',
            'Aesthetic Group Gymnastics',
            'CrossFit',
            'Powerlifting',
            'Weightlifting',
            'Model Aircraft Sports',
            'Air Sports',
            'Model Car Racing',
            'Ice Stock Sport',
            'Aquabike',
            'Aquathlon',
            'Racketball',
            'Acrobatics',
            'Acrobatic Rock and Roll',
            'Apnea (Freediving)',
            'Crossbow Shooting',
            'Armwrestling',
            'Sport Aerobics',
            'Basque Pelota',
            'BASE Jumping',
            'Biathlon',
            'Blitz Sprint',
            'Bobsleigh',
            'Bodybuilding',
            'Savate',
            'Bowling',
            'Bowls',
            'Bocce',
            'Bridge',
            'Wakeboarding',
            'Helicopter Sport',
            'Windsurfing',
            'BMX',
            'Powerboating',
            'Water Skiing',
            'Ballooning',
            'Kettlebell Sport',
            'Go',
            'Goalball',
            'Gorodki',
            'Darts',
            'Hang Gliding',
            'Sled Dog Racing',
            'Healthy Lifestyle',
            'Winter Swimming',
            'Indian Biathlon',
            'Kiting',
            'Kendo',
            'Curling',
            'Dog Sport',
            'Corporate Sports',
            'Korfball',
            'Cricket',
            'Croquet',
            'Russian Lapta',
            'Lawn Bowls',
            'Lacrosse',
            'Mountain Biking',
            'Mountainboarding',
            'Casting Sport',
            'M-1 Mixed Fight',
            'Minigolf',
            'Table Football',
            'Table Hockey',
            'Tatar Koresh Wrestling',
            'Novuss',
            'Knife Fighting',
            'Netball',
            'Oina',
            'Orienteering',
            'Paragliding',
            'Parachuting',
            'Paintball',
            'Tug of War',
            'Petanque',
            'Finswimming',
            'Gliding',
            'Beach Soccer',
            'Spearfishing',
            'Underwater Orienteering',
            'Underwater Rugby',
            'Underwater Photography',
            'Underwater Sports',
            'Underwater Hockey',
            'Fire and Rescue Sport',
            'Sports Poker',
            'Polyathlon',
            'Diving',
            'Trampoline Gymnastics',
            'Rafting',
            'Regball',
            'Roller Sports',
            'Sport Fishing',
            'Renju',
            'Luge',
            'Northern Combined',
            'Strongman',
            'Artistic Swimming',
            'Skysurfing',
            'Squash',
            'Skeleton',
            'Modern Pentathlon',
            'Lifesaving',
            'Sport for All',
            'Sports Chanbara',
            'Sporting Clays',
            'Shooting Sports',
            'Streetball',
            'Model Boat Racing',
            'Sumo',
            'Sport Tourism',
            'Ukado',
            'Fencing',
            'Fistball',
            'Fitball',
            'Flying Disc',
            'Floorball',
            'Khapsagay',
            'Nordic Walking',
            'Cheerleading',
            'Shuffleboard',
            'Draughts',
            'Extreme Sports',
            'Ethnosport',
        ];
    }
}
